apiVersion: 1
groups:
    - orgId: 1
      name: Stock Trading Simulator Game
      folder: Stock Trading Simulator Alerts
      interval: 1m
      rules:
        - uid: afxuz7cz0olq8f
          title: HTTP 5xx Error Detected
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: dfxuudmyf6ghsd
              model:
                editorMode: code
                expr: sum(rate(flask_http_request_total{status=~"5.."}[1m])) or vector(0)
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            description: The application is returning server-side HTTP 5xx errors. Investigate the application logs and recent changes.
            summary: HTTP 5xx error detected in Stock Trading Simulator
          labels:
            severity: critical
          isPaused: false
          notification_settings:
            receiver: empty
